### PR TITLE
Added types

### PR DESCRIPTION
**Pull request by SuperDJ**
Added types where possible

### CODE REVIEW

**Comment by staudenmeir** [comment]
Thanks for your PR. I would like to have fully-typed methods, but the big issue is backwards compatibility:
- I can't tag it as a `1.x` release because it would break people's code that is overriding any of the package's methods.
- But I don't want to tag a `2.0` release either because it would require all users to update their `composer.json` file to keep getting package updates.

**Comment by ecomleader** [comment]
Hey, I just want to say thank you to @staudenmeir and every contributor building this awesome package. You are life savers!

**Comment by rats4final** [comment]
Hello @staudenmeir   Any reason this and other of your packages aren't in the main framework? Have you made a pull request? Or is it because backwards compatibility? Because this is one hell of a package and I think it's a crime that is not present in the main framework

**Comment by staudenmeir** [comment]
@rats4final Some of my packages started as rejected PRs and at some point I stopped trying and just created a package.

**Comment by staudenmeir** [comment]
@SuperDJ I'm closing this PR until I find a solution for the backwards compatibility issue.

**Pull request closed without merging**
