### PR TITLE
support for 11.x added

### PR DESCRIPTION
**Pull request by anilkumarthakur60**
illuminate/database version upgraded

### CODE REVIEW

**Comment by staudenmeir** [comment]
Hi @anilkumarthakur60,
Thanks for your PR. The package already provides a version for Laravel 11:
https://github.com/staudenmeir/eloquent-has-many-deep?tab=readme-ov-file#versions

**Comment by negoziator** [comment]
@staudenmeir How come is this package requiring `^11`  and not just allowing both `^10` and `^11` ?

**Comment by negoziator** [comment]
@staudenmeir That's super fine, but in my opinion you should make a major version update then. Let me explain why:

Last night our renovate tried to upgrade `eloquent-has-many-deep` from `1.19 ->1.20` which failed because of the **major** upgrade to Laravel 11. That wouldn't have happend if `eloquent-has-many-deep` was a major as well.

I don't know if it's only us that has configured Renovate to not automatically make pull requests for **major** upgrades.

So for instance this PR that was opened by Renovate yesterday contained a list of updates, that would work perfectly fine since they are all **minor** updates - but we could not apply the updates because of the **major** update in `eloquent-has-many-deep`.

Does it make sense? 😄 

image

**Comment by negoziator** [comment]
Just so you know. I don't have any problems with your decisions on how you decide to manage your repository. I just wanted to give my 5 cents. I really appreciate your work! 

Keep it up 😎

**Comment by staudenmeir** [comment]
> Last night our renovate tried to upgrade eloquent-has-many-deep from 1.19 ->1.20 which failed because of the major upgrade to Laravel 11.

Does Renovate not check if the new version is actually compatible with your project? I've never used it and am quite surprised by this behavior. I (and others) don't consider it a breaking change to drop support for a Laravel (or PHP) version since `composer update [eloquent-has-many-deep]` correctly ignores versions that aren't compatible.

Here's a great article about this topic with a (definitive) source from semver.org:
https://sebastiandedeyne.com/composer-semver-and-underlying-dependency-changes/

> As long as the dependency update doesn't affect your package's public API, no major version bump is required.

**Pull request closed without merging**
