### PR TITLE
Increase PHPStan level to 5

### PR DESCRIPTION
**Pull request by staudenmeir**
There is only one type of PHPStan error:

> Parameter #1 $relations of method Illuminate\Database\Eloquent\Collection<int,Tests\Concatenation\LaravelAdjacencyList\Models\User>::load() expects array<(callable(Illuminate\Database\Eloquent\Builder<Tests\Concatenation\LaravelAdjacencyList\Models\User>): mixed)|string>|string, array{ancestorPosts: Closure(Staudenmeir\EloquentHasManyDeep\HasManyDeep): Staudenmeir\EloquentHasManyDeep\HasManyDeep<Illuminate\Database\Eloquent\Model>} given.

The affected code looks like this:

```php
$users = User::all()->load([
    'ancestorPosts' => fn (HasManyDeep $query) => $query->orderBy('id'),
]);
```

The first issue is that the parameter type of `Collection::load()` is incorrect. The callable function actually gets passed a relationship, not an Eloquent builder:

```php
* @param  array<array-key, (callable(\Illuminate\Database\Eloquent\Relations\Relation): mixed)|string>|string  $relations
```

However, this fix doesn't resolve the error:

> Parameter #1 $relations of method Illuminate\Database\Eloquent\Collection<int,Tests\Concatenation\LaravelAdjacencyList\Models\User>::load() expects array<(callable(Illuminate\Database\Eloquent\Relations\Relation):  
         mixed)|string>|string, array{ancestorPosts: Closure(Staudenmeir\EloquentHasManyDeep\HasManyDeep): Staudenmeir\EloquentHasManyDeep\HasManyDeep<Illuminate\Database\Eloquent\Model>} given.

The error only goes away when you change the parameter's type to `Relation` (despite `HasManyDeep` being a subclass of `Relation`):

```php
$users = User::all()->load([
    'ancestorPosts' => fn (Relation $query) => $query->orderBy('id'),
]);
```

With this change, however, PHPStan can't handle methods calls anymore despite the `Relation` class's [Eloquent builder mixin](https://github.com/laravel/framework/blob/4529498671704a2ea4bae4af1e3f8ee48ca8dfd0/src/Illuminate/Database/Eloquent/Relations/Relation.php#L21):

> Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation::orderBy(). 

@calebdw As discussed.

@SanderMuller Maybe you have an idea?

### CODE REVIEW

**Comment by staudenmeir** [comment]
@calebdw Regarding the PHPDoc fix for `Collection::load()`: I used `...Relations\Relation): mixed...` instead of `...Relations\Relation<*, *, *>): mixed...` because PhpStorm can't parse the asterisks. Not sure if they're invalid here or it's a PhpStorm bug.

**Comment by calebdw** [comment]
The problem is that the array is being parsed incorrectly and it thinks an `array<callable>` is expected instead of an `array<array-key, callable>`.

Try to update to:

```php
// remove the space
/** @param  array<array-key,(callable(\Illuminate\Database\Eloquent\Relations\Relation): mixed)|string>|string  $relations */

// or try wrapping the array in parens
/** @param  (array<array-key, (callable(\Illuminate\Database\Eloquent\Relations\Relation): mixed)|string>)|string  $relations */
```

If this doesn't work then it's likely a phpstan parse error, try to replicate on https://phpstan.org/try and open an issue with phpstan

**Comment by staudenmeir** [comment]
Thanks @calebdw. These updates don't fix the error, unfortunately.

**Comment by staudenmeir** [comment]
Thanks @calebdw. I typed the closures to get autocompletion from PhpStorm.

Do you know why the Eloquent builder mixin doesn't work here with `fn (Relation $query)`?

> Call to an undefined method Illuminate\Database\Eloquent\Relations\Relation::orderBy().

**Comment by calebdw** [comment]
@staudenmeir, the mixin is working fine when I add it to the framework tests. The issue may be that we're still waiting on https://github.com/larastan/larastan/pull/1990 to be merged so that Larastan supports Laravel >= 11.15

**Comment by SanderMuller** [comment]
@staudenmeir I also had to ignore this error in my other projects where I went to level 5/6

I've created a PR to fix this: #245 
It also adds the `phpstan/phpstan-phpunit` extension

**Comment by staudenmeir** [comment]
When https://github.com/laravel/framework/pull/52724 gets released, we can remove the ignored error.

**Comment by staudenmeir** [comment]
Thanks @calebdw and @SanderMuller.

**Pull request merged**
